# Generated by Django 2.0.4 on 2019-05-09 13:49

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Place', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('price', models.IntegerField()),
                ('originalprice', models.IntegerField()),
                ('Food', tinymce.models.HTMLField()),
                ('Amenities', tinymce.models.HTMLField()),
                ('Details', tinymce.models.HTMLField()),
                ('Location', tinymce.models.HTMLField()),
                ('Meal', models.CharField(default='Free Meals', max_length=150)),
                ('Activities', models.CharField(default='Activites', max_length=150)),
                ('Pool', models.CharField(default='Swimming Pool', max_length=150)),
                ('Music', models.CharField(default='Dj Music', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('Bed', models.CharField(max_length=150)),
                ('Extra', tinymce.models.HTMLField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='Destination.Destination')),
            ],
        ),
        migrations.AddField(
            model_name='camp',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llink', to='Destination.Destination'),
        ),
    ]
