# Generated by Django 2.0.4 on 2019-05-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='Near',
            field=models.CharField(default='Free Meals', max_length=150),
        ),
        migrations.AddField(
            model_name='type',
            name='place',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
