# Generated by Django 2.0.4 on 2019-05-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0002_auto_20190509_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='LocationImage',
            field=models.ImageField(default='noimage.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
